
import java.util.ArrayList;

/**
 * @authors: Jacob Bennett
 * Keith Kwan
 * Kyle Allen
 * Eric Nguyen
 * Kaveen Heenatigala
 * Cole Harris
 */

public class GUI extends javax.swing.JFrame {
    String selectedButton = "Counselors";
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }
     
    int counter = 0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PersonTypeButtonGroup = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jSpinner1 = new javax.swing.JSpinner();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabStudentForm = new javax.swing.JPanel();
        lblFirstNameStudentForm = new javax.swing.JLabel();
        lblLastNameStudentForm = new javax.swing.JLabel();
        lblAgeStudentForm = new javax.swing.JLabel();
        lblGradYearStudentForm = new javax.swing.JLabel();
        lblCurrentYearStudentForm = new javax.swing.JLabel();
        lblMajorStudentForm = new javax.swing.JLabel();
        txtFirstNameStudentForm = new javax.swing.JTextField();
        txtLastNameStudentForm = new javax.swing.JTextField();
        txtAgeStudentForm = new javax.swing.JTextField();
        txtGradYearStudentForm = new javax.swing.JTextField();
        txtMajorStudentForm = new javax.swing.JTextField();
        lblStudentForm = new javax.swing.JLabel();
        btnAddStudentStudentForm = new javax.swing.JButton();
        cboCurYearStudentForm = new javax.swing.JComboBox<>();
        tabTeacherForm = new javax.swing.JPanel();
        btnAddTeacherTeacherForm = new javax.swing.JButton();
        txtFirstNameTeacherForm = new javax.swing.JTextField();
        txtLastNameTeacherForm = new javax.swing.JTextField();
        txtAgeTeacherForm = new javax.swing.JTextField();
        lblFirstNameTeacherForm = new javax.swing.JLabel();
        lblLastNameTeacherForm = new javax.swing.JLabel();
        lblAgeTeacherForm = new javax.swing.JLabel();
        lblTeacherForm = new javax.swing.JLabel();
        lblTenureTeacherForm = new javax.swing.JLabel();
        lblSalaryTeacherForm = new javax.swing.JLabel();
        lblDepartmentTeacherForm = new javax.swing.JLabel();
        txtTenureTeacherForm = new javax.swing.JTextField();
        txtDepartmentTeacherForm = new javax.swing.JTextField();
        txtSalaryTeacherForm = new javax.swing.JTextField();
        tabCounselorForm = new javax.swing.JPanel();
        lblFirstNameCounselorForm = new javax.swing.JLabel();
        lblLastNameCounselorForm = new javax.swing.JLabel();
        txtFirstNameCounselorForm = new javax.swing.JTextField();
        txtLastNameCounselorForm = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        lblAgeCounselorForm = new javax.swing.JLabel();
        txtAgeCounselorForm = new javax.swing.JTextField();
        lblTenureCounselorForm = new javax.swing.JLabel();
        txtTenureCounselorForm = new javax.swing.JTextField();
        txtSalaryCounselorForm = new javax.swing.JTextField();
        lblSalaryCounselorForm = new javax.swing.JLabel();
        lblStudentsCounselorForm = new javax.swing.JLabel();
        txtStudentsCounselorForm = new javax.swing.JTextField();
        btnAddCounselorCounselorForm = new javax.swing.JButton();
        tabIDLookup = new javax.swing.JPanel();
        txtFirstNameIDLookup = new javax.swing.JTextField();
        lblFirstNameIDLookup = new javax.swing.JLabel();
        cboPersonSelectorIDLookup = new javax.swing.JComboBox<>();
        radStudentsIDLookup = new javax.swing.JRadioButton();
        radTeachersIDLookup = new javax.swing.JRadioButton();
        lblLastNameIDLookup = new javax.swing.JLabel();
        txtLastNameIDLookup = new javax.swing.JTextField();
        lblIDLookup = new javax.swing.JLabel();
        radCounselorsIDLookup = new javax.swing.JRadioButton();
        txtAgeIDLookup = new javax.swing.JTextField();
        lblAgeIDLookup = new javax.swing.JLabel();
        lblCurYearAndSalaryIDLookup = new javax.swing.JLabel();
        txtCurYearAndSalaryIDLookup = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        lblGradDateAndDepartmentAndStudentsIDLookup = new javax.swing.JLabel();
        txtGradYearAndDepartmentAndStudentsIDLookup = new javax.swing.JTextField();
        lblMajorAndTenureIDLookup = new javax.swing.JLabel();
        txtMajorAndTenureIDLookup = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        tabClassList = new javax.swing.JPanel();
        lblTeacherID = new javax.swing.JLabel();
        lblClassList = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtClassList = new javax.swing.JTextArea();
        cboTeacherID = new javax.swing.JComboBox<>();
        lblClassListTItle = new javax.swing.JLabel();
        tabClassEnrollment = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtStudentIDNum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtC1Name = new javax.swing.JTextField();
        cboC1Dpt = new javax.swing.JComboBox<>();
        cboC1Prof = new javax.swing.JComboBox<>();
        btnAddClasses = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee DataBase");

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setToolTipText(null);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPane1.setFocusable(false);
        jTabbedPane1.setName(""); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(522, 250));

        tabStudentForm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabStudentForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFirstNameStudentForm.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFirstNameStudentForm.setText("First Name:");
        tabStudentForm.add(lblFirstNameStudentForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, 20));

        lblLastNameStudentForm.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLastNameStudentForm.setText("Last Name:");
        tabStudentForm.add(lblLastNameStudentForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 80, 20));

        lblAgeStudentForm.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAgeStudentForm.setText("Age:");
        tabStudentForm.add(lblAgeStudentForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 80, 20));

        lblGradYearStudentForm.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblGradYearStudentForm.setText("Grad. Year:");
        tabStudentForm.add(lblGradYearStudentForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 80, 20));

        lblCurrentYearStudentForm.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCurrentYearStudentForm.setText("Current Year:");
        tabStudentForm.add(lblCurrentYearStudentForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 80, 20));

        lblMajorStudentForm.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMajorStudentForm.setText("Major:");
        tabStudentForm.add(lblMajorStudentForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 80, 20));
        tabStudentForm.add(txtFirstNameStudentForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 100, -1));
        tabStudentForm.add(txtLastNameStudentForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 100, -1));
        tabStudentForm.add(txtAgeStudentForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 100, -1));
        tabStudentForm.add(txtGradYearStudentForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 100, -1));
        tabStudentForm.add(txtMajorStudentForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 100, -1));

        lblStudentForm.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblStudentForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStudentForm.setText("Student Form");
        tabStudentForm.add(lblStudentForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 511, 18));

        btnAddStudentStudentForm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddStudentStudentForm.setText("Add Student");
        btnAddStudentStudentForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentStudentFormActionPerformed(evt);
            }
        });
        tabStudentForm.add(btnAddStudentStudentForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 110, -1));

        cboCurYearStudentForm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Freshman", "Sophmore", "Junior", "Senior" }));
        cboCurYearStudentForm.setSelectedIndex(-1);
        tabStudentForm.add(cboCurYearStudentForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 100, -1));

        jTabbedPane1.addTab("Student Form", null, tabStudentForm, "New Student Form");

        tabTeacherForm.setToolTipText(null);
        tabTeacherForm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabTeacherForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddTeacherTeacherForm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddTeacherTeacherForm.setText("Add Teacher");
        btnAddTeacherTeacherForm.setToolTipText("Creates new Teacher");
        btnAddTeacherTeacherForm.setBorderPainted(false);
        btnAddTeacherTeacherForm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddTeacherTeacherForm.setName("btnAddTeacherTeacherForm"); // NOI18N
        btnAddTeacherTeacherForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTeacherTeacherFormActionPerformed(evt);
            }
        });
        tabTeacherForm.add(btnAddTeacherTeacherForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 110, -1));
        tabTeacherForm.add(txtFirstNameTeacherForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 100, -1));
        tabTeacherForm.add(txtLastNameTeacherForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 100, -1));
        tabTeacherForm.add(txtAgeTeacherForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 100, -1));

        lblFirstNameTeacherForm.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFirstNameTeacherForm.setText("First Name:");
        tabTeacherForm.add(lblFirstNameTeacherForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, 20));

        lblLastNameTeacherForm.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLastNameTeacherForm.setText("Last Name:");
        tabTeacherForm.add(lblLastNameTeacherForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 80, 20));

        lblAgeTeacherForm.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAgeTeacherForm.setText("Age:");
        tabTeacherForm.add(lblAgeTeacherForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 80, 20));

        lblTeacherForm.setBackground(new java.awt.Color(255, 255, 255));
        lblTeacherForm.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblTeacherForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTeacherForm.setText("Teacher Form");
        tabTeacherForm.add(lblTeacherForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 490, 18));

        lblTenureTeacherForm.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTenureTeacherForm.setText("Tenure: ");
        tabTeacherForm.add(lblTenureTeacherForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 80, 20));

        lblSalaryTeacherForm.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSalaryTeacherForm.setText("Salary: ");
        lblSalaryTeacherForm.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        tabTeacherForm.add(lblSalaryTeacherForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 80, 20));

        lblDepartmentTeacherForm.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDepartmentTeacherForm.setText("Department: ");
        tabTeacherForm.add(lblDepartmentTeacherForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 80, 20));
        tabTeacherForm.add(txtTenureTeacherForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 100, -1));
        tabTeacherForm.add(txtDepartmentTeacherForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 100, -1));
        tabTeacherForm.add(txtSalaryTeacherForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 100, -1));

        jTabbedPane1.addTab("Teacher Form", null, tabTeacherForm, "New Teacher Form");

        tabCounselorForm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabCounselorForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFirstNameCounselorForm.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFirstNameCounselorForm.setText("First Name:");
        tabCounselorForm.add(lblFirstNameCounselorForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, 20));

        lblLastNameCounselorForm.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLastNameCounselorForm.setText("Last Name:");
        tabCounselorForm.add(lblLastNameCounselorForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 80, 20));
        tabCounselorForm.add(txtFirstNameCounselorForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 100, -1));
        tabCounselorForm.add(txtLastNameCounselorForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 100, -1));

        jLabel13.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Counselor Form");
        tabCounselorForm.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 490, 18));

        lblAgeCounselorForm.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAgeCounselorForm.setText("Age:");
        tabCounselorForm.add(lblAgeCounselorForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 80, 20));
        tabCounselorForm.add(txtAgeCounselorForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 100, -1));

        lblTenureCounselorForm.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTenureCounselorForm.setText("Tenure:");
        tabCounselorForm.add(lblTenureCounselorForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 80, 20));
        tabCounselorForm.add(txtTenureCounselorForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 100, -1));
        tabCounselorForm.add(txtSalaryCounselorForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 100, -1));

        lblSalaryCounselorForm.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSalaryCounselorForm.setText("Salary:");
        tabCounselorForm.add(lblSalaryCounselorForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 80, 20));

        lblStudentsCounselorForm.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblStudentsCounselorForm.setText("# of Students:");
        tabCounselorForm.add(lblStudentsCounselorForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 80, 20));
        tabCounselorForm.add(txtStudentsCounselorForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 100, -1));

        btnAddCounselorCounselorForm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddCounselorCounselorForm.setText("Add Counselor");
        btnAddCounselorCounselorForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCounselorCounselorFormActionPerformed(evt);
            }
        });
        tabCounselorForm.add(btnAddCounselorCounselorForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 130, -1));

        jTabbedPane1.addTab("Counselor Form", null, tabCounselorForm, "New Counselor Form");

        tabIDLookup.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabIDLookup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFirstNameIDLookup.setEditable(false);
        txtFirstNameIDLookup.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtFirstNameIDLookup.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtFirstNameIDLookup.setRequestFocusEnabled(false);
        tabIDLookup.add(txtFirstNameIDLookup, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 72, -1));

        lblFirstNameIDLookup.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblFirstNameIDLookup.setText("First Name:");
        tabIDLookup.add(lblFirstNameIDLookup, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 70, 90, -1));

        cboPersonSelectorIDLookup.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTeachIDIDLookupItemStateChanged(evt);
            }
        });
        cboPersonSelectorIDLookup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPersonSelectorIDLookupActionPerformed(evt);
            }
        });
        tabIDLookup.add(cboPersonSelectorIDLookup, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 79, -1));

        PersonTypeButtonGroup.add(radStudentsIDLookup);
        radStudentsIDLookup.setText("Students");
        radStudentsIDLookup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radStudentsIDLookupActionPerformed(evt);
            }
        });
        tabIDLookup.add(radStudentsIDLookup, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 80, -1));

        PersonTypeButtonGroup.add(radTeachersIDLookup);
        radTeachersIDLookup.setText("Teachers");
        radTeachersIDLookup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radTeachersIDLookupActionPerformed(evt);
            }
        });
        tabIDLookup.add(radTeachersIDLookup, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 79, -1));

        lblLastNameIDLookup.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblLastNameIDLookup.setText("Last Name:");
        tabIDLookup.add(lblLastNameIDLookup, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 90, -1));

        txtLastNameIDLookup.setEditable(false);
        txtLastNameIDLookup.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtLastNameIDLookup.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tabIDLookup.add(txtLastNameIDLookup, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 73, -1));

        lblIDLookup.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblIDLookup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIDLookup.setText("ID Lookup");
        tabIDLookup.add(lblIDLookup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 490, 18));

        PersonTypeButtonGroup.add(radCounselorsIDLookup);
        radCounselorsIDLookup.setSelected(true);
        radCounselorsIDLookup.setText("Counselors");
        radCounselorsIDLookup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radCounselorsIDLookupActionPerformed(evt);
            }
        });
        tabIDLookup.add(radCounselorsIDLookup, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        txtAgeIDLookup.setEditable(false);
        txtAgeIDLookup.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtAgeIDLookup.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtAgeIDLookup.setRequestFocusEnabled(false);
        tabIDLookup.add(txtAgeIDLookup, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 72, -1));

        lblAgeIDLookup.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAgeIDLookup.setText("Age:");
        tabIDLookup.add(lblAgeIDLookup, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 70, -1));

        lblCurYearAndSalaryIDLookup.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCurYearAndSalaryIDLookup.setText("Salary:");
        tabIDLookup.add(lblCurYearAndSalaryIDLookup, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 90, -1));

        txtCurYearAndSalaryIDLookup.setEditable(false);
        txtCurYearAndSalaryIDLookup.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtCurYearAndSalaryIDLookup.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCurYearAndSalaryIDLookup.setRequestFocusEnabled(false);
        tabIDLookup.add(txtCurYearAndSalaryIDLookup, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 72, -1));
        tabIDLookup.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        tabIDLookup.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 60, 120));
        tabIDLookup.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 100, 10));
        tabIDLookup.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 100, 10));

        lblGradDateAndDepartmentAndStudentsIDLookup.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblGradDateAndDepartmentAndStudentsIDLookup.setText("# of Students:");
        tabIDLookup.add(lblGradDateAndDepartmentAndStudentsIDLookup, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 190, 100, -1));

        txtGradYearAndDepartmentAndStudentsIDLookup.setEditable(false);
        txtGradYearAndDepartmentAndStudentsIDLookup.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtGradYearAndDepartmentAndStudentsIDLookup.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtGradYearAndDepartmentAndStudentsIDLookup.setRequestFocusEnabled(false);
        tabIDLookup.add(txtGradYearAndDepartmentAndStudentsIDLookup, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 72, -1));

        lblMajorAndTenureIDLookup.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMajorAndTenureIDLookup.setText("Tenure:");
        tabIDLookup.add(lblMajorAndTenureIDLookup, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 50, -1));

        txtMajorAndTenureIDLookup.setEditable(false);
        txtMajorAndTenureIDLookup.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtMajorAndTenureIDLookup.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtMajorAndTenureIDLookup.setRequestFocusEnabled(false);
        tabIDLookup.add(txtMajorAndTenureIDLookup, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 72, -1));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        tabIDLookup.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 20, 120));

        jTabbedPane1.addTab("ID Lookup", null, tabIDLookup, "Lookup Person By ID");

        tabClassList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTeacherID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTeacherID.setText("Teacher ID:");
        tabClassList.add(lblTeacherID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, 22));

        lblClassList.setText("Class List:");
        tabClassList.add(lblClassList, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 70, 20));

        txtClassList.setEditable(false);
        txtClassList.setColumns(20);
        txtClassList.setRows(5);
        jScrollPane1.setViewportView(txtClassList);

        tabClassList.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 370, 120));

        cboTeacherID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTeacherIDItemStateChanged(evt);
            }
        });
        tabClassList.add(cboTeacherID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 110, -1));

        lblClassListTItle.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblClassListTItle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClassListTItle.setText("Class List");
        tabClassList.add(lblClassListTItle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 490, 18));

        jTabbedPane1.addTab("Class List", null, tabClassList, "Teacher Class List");

        tabClassEnrollment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Student ID:");
        tabClassEnrollment.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));
        tabClassEnrollment.add(txtStudentIDNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 120, 30));

        jLabel2.setText("Course Name:");
        tabClassEnrollment.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, 20));

        jLabel3.setText("Course Department:");
        tabClassEnrollment.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 110, 20));

        jLabel4.setText("Course Professor:");
        tabClassEnrollment.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, 20));
        tabClassEnrollment.add(txtC1Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 119, -1));

        cboC1Dpt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboC1DptItemChanged(evt);
            }
        });
        cboC1Dpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboC1DptProfFinder(evt);
            }
        });
        tabClassEnrollment.add(cboC1Dpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 119, -1));

        cboC1Prof.setToolTipText("");
        tabClassEnrollment.add(cboC1Prof, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 119, -1));

        btnAddClasses.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddClasses.setText("Add Classes");
        tabClassEnrollment.add(btnAddClasses, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        jLabel21.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Course Enrollment Form");
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tabClassEnrollment.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 490, 18));

        jTabbedPane1.addTab("Class Enrollment", null, tabClassEnrollment, "Student Class Enrollment");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Tabs");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboTeachIDIDLookupItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTeachIDIDLookupItemStateChanged
        if(cboPersonSelectorIDLookup.getSelectedIndex() != -1){
            switch (selectedButton) {
                
                case "Students":
                    if(cboPersonSelectorIDLookup.getItemCount()!=0){
                        
                        Student displayPerson = DataBase.StudentIDLookUp(cboPersonSelectorIDLookup.getSelectedItem().toString());
                        txtFirstNameIDLookup.setText(displayPerson.getFirstName());
                        txtLastNameIDLookup.setText(displayPerson.getLastName());
                        txtAgeIDLookup.setText(Integer.toString(displayPerson.getAge()));
                        txtMajorAndTenureIDLookup.setText(displayPerson.getMajor());
                        txtGradYearAndDepartmentAndStudentsIDLookup.setText(Integer.toString(displayPerson.getGradDate()));
                        txtCurYearAndSalaryIDLookup.setText(displayPerson.getCurrentYear());
                        
                    }   break;
                    
                case "Teachers":
                    if(cboPersonSelectorIDLookup.getItemCount() != 0){
                        
                        Teacher displayPerson = DataBase.TeacherIDLookUp(cboPersonSelectorIDLookup.getSelectedItem().toString());
                        txtFirstNameIDLookup.setText(displayPerson.getFirstName());
                        txtLastNameIDLookup.setText(displayPerson.getLastName());
                        txtAgeIDLookup.setText(Integer.toString(displayPerson.getAge()));
                        txtMajorAndTenureIDLookup.setText(Integer.toString(displayPerson.getTenure()));
                        txtGradYearAndDepartmentAndStudentsIDLookup.setText(displayPerson.getDepartment());
                        txtCurYearAndSalaryIDLookup.setText("$" + Double.toString(displayPerson.getSalary()));
                        
                    }   break;
                case "Counselors":
                    
                    if(cboPersonSelectorIDLookup.getItemCount() != 0){
                        
                        Counselor displayPerson = DataBase.CounselorIDLookUp(cboPersonSelectorIDLookup.getSelectedItem().toString());
                        txtFirstNameIDLookup.setText(displayPerson.getFirstName());
                        txtLastNameIDLookup.setText(displayPerson.getLastName());
                        txtAgeIDLookup.setText(Integer.toString(displayPerson.getAge()));
                        txtMajorAndTenureIDLookup.setText(Integer.toString(displayPerson.getTenure()));
                        txtGradYearAndDepartmentAndStudentsIDLookup.setText(Integer.toString(displayPerson.getNumberOfStudents()));
                        txtCurYearAndSalaryIDLookup.setText("$" + Double.toString(displayPerson.getSalary()));
                        
                    }   break;
                    
                default:
                    System.err.print("Problem on line 382");
                    break;
            }
        }
    }//GEN-LAST:event_cboTeachIDIDLookupItemStateChanged

    private void radStudentsIDLookupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radStudentsIDLookupActionPerformed
        selectedButton = "Students";
        
        //Sets lables for coresponding Teacher Fields
        lblCurYearAndSalaryIDLookup.setText("Current Year:");
        lblGradDateAndDepartmentAndStudentsIDLookup.setText("Graduation Year:");
        lblMajorAndTenureIDLookup.setText("Major:");
        
        //Removes all items in the combobox
        cboPersonSelectorIDLookup.removeAllItems();
        
        //Adds all the contents of studentlist ids to the combobox
        for(int i = 0; i < DataBase.GetStudentList().size(); i ++){
            cboPersonSelectorIDLookup.addItem(DataBase.GetStudentList().get(i).getID());
        }
        
        //Initializes the Combobox to -1
        cboPersonSelectorIDLookup.setSelectedIndex(-1);
        
        //Clears all output fields
        txtFirstNameIDLookup.setText("");
        txtLastNameIDLookup.setText("");
        txtAgeIDLookup.setText("");
        txtMajorAndTenureIDLookup.setText("");
        txtCurYearAndSalaryIDLookup.setText("");
        txtGradYearAndDepartmentAndStudentsIDLookup.setText("");
    }//GEN-LAST:event_radStudentsIDLookupActionPerformed

    private void radTeachersIDLookupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radTeachersIDLookupActionPerformed
        selectedButton = "Teachers";
        
        //Sets lables for coresponding Teacher Fields
        lblCurYearAndSalaryIDLookup.setText("Salary:");
        lblGradDateAndDepartmentAndStudentsIDLookup.setText("Department:");
        lblMajorAndTenureIDLookup.setText("Tenure:");
        
        //Removes all items in the combobox
        cboPersonSelectorIDLookup.removeAllItems();
        
        
        
        //Adds all the contents of teacherlist ids to the combobox
        for(int i = 0; i < DataBase.GetTeacherList().size(); i++){
            cboPersonSelectorIDLookup.addItem(DataBase.GetTeacherList().get(i).getID());
            
        }
        //Initializes the Combobox to -1
        cboPersonSelectorIDLookup.setSelectedIndex(-1);
        
        //Clears all output fields
        txtFirstNameIDLookup.setText("");
        txtLastNameIDLookup.setText("");
        txtAgeIDLookup.setText("");
        txtMajorAndTenureIDLookup.setText("");
        txtCurYearAndSalaryIDLookup.setText("");
        txtGradYearAndDepartmentAndStudentsIDLookup.setText("");
    }//GEN-LAST:event_radTeachersIDLookupActionPerformed
    
    public void ErrorPopUp(String message){
        javax.swing.JOptionPane.showMessageDialog(null, 
                 message);                                          
    }
    
    ArrayList<Teacher> professor = new ArrayList<Teacher>();
    
    private void btnAddTeacherTeacherFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTeacherTeacherFormActionPerformed
        DataBase.AddTeacher(new Teacher(
                txtFirstNameTeacherForm.getText(), //Gets First Name from form
                txtLastNameTeacherForm.getText(), //Gets Last Name from form
                Integer.parseInt(txtAgeTeacherForm.getText()), //Gets and Parses Age into an int from form
                Double.parseDouble(txtSalaryTeacherForm.getText()), //Gets and Parses Salary into a double from form
                Integer.parseInt(txtTenureTeacherForm.getText()),  //Gets and Parses Tenure into an int from form
                txtDepartmentTeacherForm.getText()  //Gets Department from form
        ));
        
        //Clears New Teacher Form Inputs
        txtFirstNameTeacherForm.setText("");
        txtLastNameTeacherForm.setText("");
        txtAgeTeacherForm.setText("");
        txtSalaryTeacherForm.setText("");
        txtTenureTeacherForm.setText("");
        txtDepartmentTeacherForm.setText("");
        //Clears Comboboxes
        cboC1Dpt.setSelectedIndex(-1);
        cboC1Prof.setSelectedIndex(-1);
        
        //Immediatly Adds ID to the ID Lookup combo box if the teachers button is selected
        //*******KAVEENS EDITS*******//
        Teacher newTeacher = DataBase.GetTeacherList().get(DataBase.GetTeacherList().size() - 1);
        professor.add(newTeacher);
        cboTeacherID.addItem(newTeacher.getID());
        outerloop:
        if(cboC1Dpt.getItemCount() == 0)
        {
            cboC1Dpt.addItem(newTeacher.getDepartment());
        }
        else
        {
            
            for(int ctr = 0; ctr < counter + 1; ctr++)
            {
                if(cboC1Dpt.getItemAt(ctr).equals(newTeacher.getDepartment()))
                {
                    break outerloop;
                }
            }
            cboC1Dpt.addItem(newTeacher.getDepartment());
            counter++;
        }
       
        
        //****************************//
        if(selectedButton.equals("Teachers")){
            cboPersonSelectorIDLookup.addItem(newTeacher.getID());
        }
        
    }//GEN-LAST:event_btnAddTeacherTeacherFormActionPerformed

    private void radCounselorsIDLookupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radCounselorsIDLookupActionPerformed
        selectedButton = "Counselors";
        
        //Sets lables for coresponding Counselor Fields
        lblCurYearAndSalaryIDLookup.setText("Salary:");
        lblGradDateAndDepartmentAndStudentsIDLookup.setText("# of Students:");
        lblMajorAndTenureIDLookup.setText("Tenure:");
        
        //Removes all items in the combobox
        cboPersonSelectorIDLookup.removeAllItems();
        
        //Adds all the contents of counelorlist ids to the combobox
        for(int i = 0; i < DataBase.GetCounselorList().size(); i++){
            cboPersonSelectorIDLookup.addItem(DataBase.GetCounselorList().get(i).getID());
        }
        
        //Initializes the Combobox to -1
        cboPersonSelectorIDLookup.setSelectedIndex(-1);
        
        //Clears all output fields
        txtFirstNameIDLookup.setText("");
        txtLastNameIDLookup.setText("");
        txtAgeIDLookup.setText("");
        txtMajorAndTenureIDLookup.setText("");
        txtCurYearAndSalaryIDLookup.setText("");
        txtGradYearAndDepartmentAndStudentsIDLookup.setText("");
    }//GEN-LAST:event_radCounselorsIDLookupActionPerformed

    private void btnAddCounselorCounselorFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCounselorCounselorFormActionPerformed
        DataBase.AddCounselor(new Counselor(
                txtFirstNameCounselorForm.getText(), //Gets First Name from form
                txtLastNameCounselorForm.getText(), //Gets Last Name from form
                Integer.parseInt(txtAgeCounselorForm.getText()), //Gets and Parses Age into an int from form
                Double.parseDouble(txtSalaryCounselorForm.getText()), //Gets and Parses Salary into a double from form
                Integer.parseInt(txtTenureCounselorForm.getText()),  //Gets and Parses Tenure into an int from form
                Integer.parseInt(txtStudentsCounselorForm.getText())  //Gets and Parses Students into an int from form
        ));
        
        //Clears New Counselor Form Inputs
        txtFirstNameCounselorForm.setText("");
        txtLastNameCounselorForm.setText("");
        txtAgeCounselorForm.setText("");
        txtSalaryCounselorForm.setText("");
        txtTenureCounselorForm.setText("");
        txtStudentsCounselorForm.setText("");
        
        //Immediatly Adds ID to the ID Lookup combo box if the counselors button is selected
        if(selectedButton.equals("Counselors")){
            Counselor newCounselor = DataBase.GetCounselorList().get(DataBase.GetCounselorList().size() - 1);
            cboPersonSelectorIDLookup.addItem(newCounselor.getID());
        }
    }//GEN-LAST:event_btnAddCounselorCounselorFormActionPerformed

    private void btnAddStudentStudentFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentStudentFormActionPerformed
        DataBase.AddStudent(new Student(
                txtFirstNameStudentForm.getText(), //Gets First Name from form
                txtLastNameStudentForm.getText(), //Gets Last Name from form
                Integer.parseInt(txtAgeStudentForm.getText()), //Gets and Parses Age into an int from form
                cboCurYearStudentForm.getSelectedItem().toString(),  //Gets current year from form
                Integer.parseInt(txtGradYearStudentForm.getText()), //Gets and Parses Grad. Year into an int from form
                txtMajorStudentForm.getText()  //Gets Major from form
        ));
        
        //Clears New Student Form Inputs
        txtFirstNameStudentForm.setText("");
        txtLastNameStudentForm.setText("");
        txtAgeStudentForm.setText("");
        txtMajorStudentForm.setText("");
        txtGradYearStudentForm.setText("");
        cboCurYearStudentForm.setSelectedIndex(-1);
        
        //Immediatly Adds ID to the ID Lookup combo box if the students button is selected
        if(selectedButton.equals("Students")){
            Student newStudent = DataBase.GetStudentList().get(DataBase.GetStudentList().size() - 1);
            cboPersonSelectorIDLookup.addItem(newStudent.getID());
        }
        
    }//GEN-LAST:event_btnAddStudentStudentFormActionPerformed

    private void cboTeacherIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTeacherIDItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTeacherIDItemStateChanged

    private void cboC1DptItemChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboC1DptItemChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cboC1DptItemChanged

    private void cboC1DptProfFinder(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboC1DptProfFinder
        // TODO add your handling code here:
       cboC1Prof.removeAllItems();
       for(int ctr = 0; ctr < professor.size(); ctr++)
       {
           if(cboC1Dpt.getSelectedItem().equals(professor.get(ctr).getDepartment()))
           {
               cboC1Prof.addItem(professor.get(ctr).getLastName() + ", " + professor.get(ctr).getFirstName());
           }
       }
       
    }//GEN-LAST:event_cboC1DptProfFinder

    private void cboPersonSelectorIDLookupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPersonSelectorIDLookupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboPersonSelectorIDLookupActionPerformed

    /**
     * @param args the command line arguments
     */
    
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUI().setVisible(true);
        });
     
     //TeacherIDs.add("0");   
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup PersonTypeButtonGroup;
    private javax.swing.JButton btnAddClasses;
    private javax.swing.JButton btnAddCounselorCounselorForm;
    private javax.swing.JButton btnAddStudentStudentForm;
    private javax.swing.JButton btnAddTeacherTeacherForm;
    private javax.swing.JComboBox<String> cboC1Dpt;
    private javax.swing.JComboBox<String> cboC1Prof;
    private javax.swing.JComboBox<String> cboCurYearStudentForm;
    private javax.swing.JComboBox<String> cboPersonSelectorIDLookup;
    private javax.swing.JComboBox<String> cboTeacherID;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAgeCounselorForm;
    private javax.swing.JLabel lblAgeIDLookup;
    private javax.swing.JLabel lblAgeStudentForm;
    private javax.swing.JLabel lblAgeTeacherForm;
    private javax.swing.JLabel lblClassList;
    private javax.swing.JLabel lblClassListTItle;
    private javax.swing.JLabel lblCurYearAndSalaryIDLookup;
    private javax.swing.JLabel lblCurrentYearStudentForm;
    private javax.swing.JLabel lblDepartmentTeacherForm;
    private javax.swing.JLabel lblFirstNameCounselorForm;
    private javax.swing.JLabel lblFirstNameIDLookup;
    private javax.swing.JLabel lblFirstNameStudentForm;
    private javax.swing.JLabel lblFirstNameTeacherForm;
    private javax.swing.JLabel lblGradDateAndDepartmentAndStudentsIDLookup;
    private javax.swing.JLabel lblGradYearStudentForm;
    private javax.swing.JLabel lblIDLookup;
    private javax.swing.JLabel lblLastNameCounselorForm;
    private javax.swing.JLabel lblLastNameIDLookup;
    private javax.swing.JLabel lblLastNameStudentForm;
    private javax.swing.JLabel lblLastNameTeacherForm;
    private javax.swing.JLabel lblMajorAndTenureIDLookup;
    private javax.swing.JLabel lblMajorStudentForm;
    private javax.swing.JLabel lblSalaryCounselorForm;
    private javax.swing.JLabel lblSalaryTeacherForm;
    private javax.swing.JLabel lblStudentForm;
    private javax.swing.JLabel lblStudentsCounselorForm;
    private javax.swing.JLabel lblTeacherForm;
    private javax.swing.JLabel lblTeacherID;
    private javax.swing.JLabel lblTenureCounselorForm;
    private javax.swing.JLabel lblTenureTeacherForm;
    private javax.swing.JRadioButton radCounselorsIDLookup;
    private javax.swing.JRadioButton radStudentsIDLookup;
    private javax.swing.JRadioButton radTeachersIDLookup;
    private javax.swing.JPanel tabClassEnrollment;
    private javax.swing.JPanel tabClassList;
    private javax.swing.JPanel tabCounselorForm;
    private javax.swing.JPanel tabIDLookup;
    private javax.swing.JPanel tabStudentForm;
    private javax.swing.JPanel tabTeacherForm;
    private javax.swing.JTextField txtAgeCounselorForm;
    private javax.swing.JTextField txtAgeIDLookup;
    private javax.swing.JTextField txtAgeStudentForm;
    private javax.swing.JTextField txtAgeTeacherForm;
    private javax.swing.JTextField txtC1Name;
    private javax.swing.JTextArea txtClassList;
    private javax.swing.JTextField txtCurYearAndSalaryIDLookup;
    private javax.swing.JTextField txtDepartmentTeacherForm;
    private javax.swing.JTextField txtFirstNameCounselorForm;
    private javax.swing.JTextField txtFirstNameIDLookup;
    private javax.swing.JTextField txtFirstNameStudentForm;
    private javax.swing.JTextField txtFirstNameTeacherForm;
    private javax.swing.JTextField txtGradYearAndDepartmentAndStudentsIDLookup;
    private javax.swing.JTextField txtGradYearStudentForm;
    private javax.swing.JTextField txtLastNameCounselorForm;
    private javax.swing.JTextField txtLastNameIDLookup;
    private javax.swing.JTextField txtLastNameStudentForm;
    private javax.swing.JTextField txtLastNameTeacherForm;
    private javax.swing.JTextField txtMajorAndTenureIDLookup;
    private javax.swing.JTextField txtMajorStudentForm;
    private javax.swing.JTextField txtSalaryCounselorForm;
    private javax.swing.JTextField txtSalaryTeacherForm;
    private javax.swing.JTextField txtStudentIDNum;
    private javax.swing.JTextField txtStudentsCounselorForm;
    private javax.swing.JTextField txtTenureCounselorForm;
    private javax.swing.JTextField txtTenureTeacherForm;
    // End of variables declaration//GEN-END:variables

}